package com.mossle.user.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountOperation .
 * 
 * @author xuzhihao
 */
@Entity
@Table(name = "ACCOUNT_OPERATION")
public class AccountOperation implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private String operation;

    /** null. */
    private Date time;

    /** null. */
    private String tenantId;

    public AccountOperation(Long id, String name,
            String operation, Date time, String tenantId) {
        this.id = id;
        this.name = name;
        this.operation = operation;
        this.time = time;
        this.tenantId = tenantId;
    }

    public AccountOperation() {
		// TODO Auto-generated constructor stub
	}

	/** @return null. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "NAME", length = 255)
    public String getName() {
        return this.name;
    }

    /**
     * @param os
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "OPERATION", length = 1024)
    public String getOperation() {
        return this.operation;
    }

    /**
     * @param client
     *            null.
     */
    public void setOperation(String operation) {
        this.operation = operation;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TIME", length = 26)
    public Date getTime() {
        return this.time;
    }

    /**
     * @param createTime
     *            null.
     */
    public void setTime(Date time) {
        this.time = time;
    }


    /** @return null. */
    @Column(name = "TENANT_ID", length = 64)
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * @param tenantId
     *            null.
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}
