package com.mossle.device.persistence.domain;

// Generated by Hibernate Tools
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DeviceInfo 设备信息.
 * 
 * @author XuZhihao
 */
@Entity
@Table(name = "DEVICE_INFO")
public class DeviceInfo implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 设备名称. */
    private String name;

    /** 编号. */
    private String number;

    /** 种类. */
    private String devcieClass;

    /** 状态. */
    private String status;

    /** 占用节点Id */
    private String occupationId;

    /** 占用节点名城 */
    private String nodeName;

    public DeviceInfo() {
    }

    public DeviceInfo(Long id) {
        this.id = id;
    }

    public DeviceInfo(Long id, String name, String number, String devcieClass,
            String status) {
        this.id = id;
        this.name = name;
        this.number = number;
        this.devcieClass = devcieClass;
        this.status = status;
    }

    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "NAME", length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "NUMBER", length = 100)
    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    @Column(name = "DEVICE_CLASS", length = 255)
    public String getDeviceClass() {
        return this.devcieClass;
    }

  
    public void setDeviceClass(String devcieClass) {
        this.devcieClass = devcieClass;
    }

    
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }


    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "OCCUPATION_ID", length = 50)
	public String getOccupationId() {
		return occupationId;
	}

	public void setOccupationId(String occupationId) {
		this.occupationId = occupationId;
	}

	  @Column(name = "NODE_NAME", length = 255)
	public String getNodeName() {
		return nodeName;
	}

	public void setNodeName(String nodeName) {
		this.nodeName = nodeName;
	}

}
