package com.mossle.plan.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanInfo 实验计划信息.
 * 
 * @author XuZhihao
 */
@Entity
@Table(name = "PLAN_INFO")
public class PlanInfo implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 实验名称. */
    private String process;

    /** 阶段. */
    private String stage;

    /** 用户 */
    private String user;

    /** 计划内容. */
    private String content;

    /** 时间 */
    private Date time;
    
    /** 计划类型. */
    private String type;
    
    /** userid */
    private String userId;
    
    /** 状态. */
    private String status;
    
    /** 创造者id. */
    private String creatUserId;

    public PlanInfo() {
    }

    public PlanInfo(Long id) {
        this.id = id;
    }

    public PlanInfo(Long id, String process, String stage, String user,
            String content, Date time) {
        this.id = id;
        this.setProcess(process);
        this.setStage(stage);
        this.setUser(user);
        this.setContent(content);
        this.setTime(time);
    }

    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "PROCESS", length = 255)
	public String getProcess() {
		return process;
	}

	public void setProcess(String process) {
		this.process = process;
	}

	 @Column(name = "STAGE", length = 50)
	public String getStage() {
		return stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

	@Column(name = "USER", length = 50)
	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "CONTENT", length = 1024)
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "TIME", length = 26)
	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "TYPE", length = 50)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "USER_ID", length = 50)
	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CREAT_USER_ID", length = 50)
	public String getCreatUserId() {
		return creatUserId;
	}

	public void setCreatUserId(String creatUserId) {
		this.creatUserId = creatUserId;
	}


}
